### ISSUE TITLE
How to compile cdma module with existing gnuradio ?

### ISSUE THREAD

**Issue by patel999jay** [anastas/gr-cdma#35]
Hi,

I had successfully installed gr-cdma module. Just had one question about instruction in the installation which says 

```bash
-- For each of the blocks listed below, open them into gnuradio-companion and compile each one (using the button in GRC that looks like a sphere and a pyramid with an arrow between them) and then reload each time (using the button that looks like a circular arrow)

"cdma_tx_hier.grc",

"chopper_correlator.grc",

"cdma_rx_hier.grc",

-- Reload all blocks in grc

-- Load the application "cdma_txrx.grc" and have fun
```

How can i do that.  Each files opened has missing modules. I am not very sure how do integrate this.
![compile_error](https://user-images.githubusercontent.com/5512610/76345587-87084180-62fb-11ea-9880-4853a2dfaf05.png)

**Comment by anastas** [comment]
Apparently you have not installed cdma succesfully!
The Import blocks in the above figure say "Import None" which means you have not succesfully imported the cdma module.

Open python:
Do:
>> import cdma

if this command gives you an error, it is safe to assume you have not succcesfully installed the software.

**Comment by patel999jay** [comment]
Hi,

Thanks for your reply. Here is what i have after doing import cdma in python.

```bash
jay@jay-MS-7885:~/gr-cdma/apps$ python
Python 2.7.17 (default, Nov  7 2019, 10:07:09) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cdma
CDMA PARAMETERS : for adaptive coded modulation
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/cdma/__init__.py", line 34, in <module>
    import cdma_parameters
  File "/usr/local/lib/python2.7/dist-packages/cdma/cdma_parameters.py", line 110, in <module>
    local_header_obj = cdma.packet_header2(bits_per_header,length_tag_name,num_tag_name, header_mod.bits_per_symbol(),tcm_type_selector_default, "tcm_type") 
AttributeError: 'module' object has no attribute 'packet_header2'
```

**Comment by patel999jay** [comment]
Perfect, I looked after my cmake log and find out that my [SWIG module](https://github.com/anastas/gr-cdma/issues/22) is out of date and i did updated with that and now i think its working fine. Thanks a lot for your help.

![cdma](https://user-images.githubusercontent.com/5512610/76364137-3bf22c80-6303-11ea-9cbc-228d760e56f1.png)

**Comment by anastas** [comment]
In your initial attached figure you seemed to have been using gnuradio 3.8 which required python3 and is not compatible with gr-cdma.

Now you seem to be using gnuradio 3.7

Can you confirm that indeed this was the case.

In any case, which version of gnuradio are you using?

**Comment by patel999jay** [comment]
Hey Anastas, 

You were right. if was newer version of `gnuradio 3.8` which i build using ubuntu but i looked it over and seems like your module is not on `python3` so i build `gnuradio` from source and checkout previous version, and try to import your module and it works.

**Comment by patel999jay** [comment]
@anastas : Are you planning to port this to newer version of `gnuradio 3.8` by any chance ?
