### ISSUE TITLE
Builds properly, but cdma_txrx throwing error

### ISSUE THREAD

**Issue by garengllc** [anastas/gr-cdma#6]
<<<<<<<<<<<<<NOT AN ISSUE........... I blew everything away and rebuilt and now this runs fine. Sorry>>>>>>>>>>>>
Everything built properly following the steps in the README, but when I try to run the cdma_txrx script, I get the following error:
CDMA PARAMETERS : for adaptive modulation
bits_per_header= 36
symbols_per_header= 36

bits_per_coded_symbol = [2, 3]  for [uncoded QPSK, rate 2/3 cc &8PSK] respectively.

payload_bytes_per_frame= 50
symbols_per_frame= 260
trellis_coded_payload_symbols_per_frame= 216  for [uncoded QPSK, rate 2/3 cc &8PSK] respectively.

trellis_coded_payload_bytes_per_frame= [54, 81]  for [uncoded QPSK, rate 2/3 cc &8PSK] respectively.

additional_symbols_per_frame= 8  for [uncoded QPSK, rate 2/3 cc &8PSK] respectively.

additional_bytes_per_frame= [1, 1]  for [uncoded QPSK, rate 2/3 cc &8PSK] respectively.

you have wasted [0.01818181818181818, 0.012195121951219513] percent of bytes per payload for [uncoded QPSK, rate 2/3 cc &8PSK] with this symbols_per_frame setting.

training_length = 260

Normalized frequency interval =  0.000240384615385
Normalized frequency unsertainty range = [ -0.00240384615385  ,  0.00240384615385 ]
Using Volk machine: avx_64_mmx_orc
Traceback (most recent call last):
  File "/home/lts/gr-cdma/apps/cdma_txrx.py", line 583, in <module>
    tb = cdma_txrx()
  File "/home/lts/gr-cdma/apps/cdma_txrx.py", line 230, in __init__
    acq=onoff,
  File "/home/lts/.grc_gnuradio/cdma_rx_hier.py", line 60, in __init__
    pulse_data=cp.pulse_data,
  File "/home/lts/.grc_gnuradio/chopper_correlator.py", line 50, in __init__
    self.cdma_vector_insert2_0_0 = cdma.vector_insert2(((Q-1)*(0,)   ), (N+pulse_L)*Q +1   ,  (N+pulse_L)*Q +1)
AttributeError: 'module' object has no attribute 'vector_insert2'

>>> Done

I am running Ubuntu 14.04 x64 in a VM.  GR is ver 3.7.7.1

**Comment by garengllc** [comment]
NOT AN ISSUE.......... I blew everything away and rebuild from scratch and all was happy. Sorry for the false alarm, I don't know what caused things to get out of whack.
